DELETE http://localhost:3001/api/users/5ff70c730fa87c36d9ad201e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmY3MGM3MzBmYTg3YzM2ZDlhZDIwMWUiLCJpYXQiOjE2MTAwMzAwNjh9.yIbO8aWgqpkwVoVdJmr_u4lDlxJ1PFNhvF3Mjo51JpM